---
- name: Return anaconda binary location and name to registered var
  command: readlink -f {{anaconda_parent_dir}}/anaconda/
  register: anaconda_binary

- name: Change anaconda owner to vagrant user
  file:
    path: "{{ anaconda_binary.stdout }}"
    state: directory
    owner: vagrant
    group: vagrant
    recurse: yes
    follow: no

- name: Install anaconda configuration file
  copy:
    src: files/.condarc
    dest: /home/vagrant/.condarc
    owner: vagrant
    group: vagrant

- name: Install conda-build
  become: yes
  become_user: vagrant
  command: /usr/local/anaconda/bin/conda install conda-build
