---
- name: install required packages using yum
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - epel-release
    - git-core
    - vim
    - curl
    - zlib
    - zlib-devel
    - gcc-c++
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - sqlite
    - sqlite-devel
    - libxml2-devel
    - libxslt-devel
    - libcurl-devel
    - httpd
    - httpd-devel
    - nano
    - tree
    - htop
    - freetype
    - freetype-devel
    - libpng-devel
    - libjpeg-devel
    - zlib-devel

- name: set default vagrant ssh directory
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: "cd /vagrant"

- name: set $DISPLAY environment variable
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: "export DISPLAY=:0.0"
