---
  - hosts: all
    vars:
      anaconda_make_sys_default : true
    become: yes
    become_method: sudo
    become_user: root
    gather_facts: yes
    roles:
      - role: basic-setup
      - role: latex
      - role: andrewrothstein.anaconda
      - role: anaconda-config
      - role: jupyter-server
      - role: ansible-module-cran
      - role: r
      - role: rstudio-server
