---
- hosts: scholars-backpack
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  vars:
    project_name: "scholars-backback"
  roles:
    - role: basic-setup
    - role: python
    - role: jupyter-server-setup
    - role: ansible-module-cran
    - role: r
    - role: rstudio
    - role: desktop
