---
- name: download R Studio Server package
  get_url:
    url: https://download2.rstudio.org/rstudio-server-rhel-1.1.383-x86_64.rpm
    dest: /tmp/rstudio-server-rhel-1.1.383-x86_64.rpm
    checksum: md5:1e973cd9532d435d8a980bf84ec85c30
    mode: '0755'

- name: install R Studio Server from package
  yum:
    name: /tmp/rstudio-server-rhel-1.1.383-x86_64.rpm
    state: present

- name: add anaconda R to rserver.conf
  lineinfile:
    name: /etc/rstudio/rserver.conf
    line: 'rsession-which-r=/usr/local/anaconda/bin/R'
    state: present
    create: yes

- name: add ld-library-path to rserver.conf
  lineinfile:
    name: /etc/rstudio/rserver.conf
    line: 'rsession-ld-library-path=/usr/local/Anaconda3-5.0.1-Linux-x86_64/lib'
    state: present
    create: yes

- name: create r-versions and add anaconda R
  lineinfile:
    name: /etc/rstudio/r-versions
    line: '/usr/local/anaconda/bin/R'
    state: present
    create: yes

- name: add default working directory to rsession.conf
  lineinfile:
    name: /etc/rstudio/rsession.conf
    line: 'session-default-working-dir=/vagrant/code'
    state: present
    create: yes

- name: reset rstudio service
  command: /bin/systemctl reset-failed rstudio-server

- name: start Server
  command: rstudio-server start
