---
- name: install r-essentials
  become: yes
  become_user: vagrant
  command: /usr/local/anaconda/bin/conda install -c r r-essentials

- name: install R packages from cran
  cran:
    name: "{{ item }}"
    state: present
  with_items:
    - plotly
