galaxy_info:
  author: Hiroaki Yutani
  description: A role to use the module installing/uninstalling R packages
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: GenericUNIX
    versions:
    - any
  - name: GenericLinux
    versions:
    - any
  galaxy_tags:
    - R

dependencies: []
